#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

mkdir -p /dev/pts
mount -t devpts none /dev/pts

ln -sf /bin/busybox /sbin/poweroff
ln -sf /bin/busybox /sbin/reboot

mkdir -p /var/cache/apk /tmp /home/lemon /run
mount -t tmpfs -o size=128M tmpfs /var/cache/apk
mount -t tmpfs -o size=64M tmpfs /tmp
mount -t tmpfs -o size=16M tmpfs /run

chmod 1777 /tmp

echo "LemonOS" > /etc/hostname
hostname LemonOS

export USER=lemon
export HOME=/home/lemon
export LOGNAME=lemon
export LANG=C.UTF-8
export LC_ALL=C.UTF-8

udevd --daemon
udevadm trigger

alsactl init 2>/dev/null

for i in 1 2 3 4 5; do
    if [ -d /sys/class/net/eth0 ] || [ -d /sys/class/net/wlan0 ]; then
        break
    fi
    sleep 1
done

ifconfig eth0 up 2>/dev/null
udhcpc -i eth0 -b -q 2>/dev/null

if [ -d /sys/class/net/wlan0 ]; then
    ifconfig wlan0 up 2>/dev/null
fi

echo "nameserver 8.8.8.8" > /etc/resolv.conf

cat << 'EOF' > /home/lemon/.bashrc
alias fastfetch="fastfetch --logo linux"
clear
export FASTFETCH_OS_RELEASE="0.8"
fastfetch
PS1='\[\033[01;33m\]\u\[\033[00m\]@\[\033[01;32m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
EOF

echo "source /usr/share/bash-completion/bash_completion" >> /home/lemon/.bashrc

startx

echo "Xorg crashed or exited. Dropping to rescue shell..."
exec /bin/bash --login
